[package]
name = "cys-span"
version = "0.1.0"
edition = "2021"

[dependencies]
cys-span-derive = { path = "derive", optional = true }

[features]
derive_macros = ["dep:cys-span-derive"]

[dev-dependencies]
trybuild = "1.0"
